##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile for dante star
##

all:
	@make -C solver
	@make -C generator

clean:
	@make clean -C solver
	@make clean -C generator

fclean:
	@make fclean -C solver
	@make fclean -C generator

re:	fclean all

.PHONY: all clean fclean re
